### ISSUE TITLE
'Path must be a directory' error on Windows

### ISSUE THREAD

**Issue by gilbh** [saadmk11/python-third-party-imports#1]
Hi,

On Windows 10, when I run the following:
```
third-party-imports gPython\gremote.py
```
I get the following:
```
error: invalid value 'gPython\gremote.py' for '<PROJECT_ROOT>': Path must be a directory
```

This also happens if I try with forward-slash (as in Linux) or the with the full path.

Thanks!

**Comment by saadmk11** [comment]
Currently you can only run this tool on the project root path, so the path can to be a path to file. Try only using `gPython`.

I planning to update this soon. :)

**Comment by gilbh** [comment]
Yup, that worked!

Thanks!!
